language: generic

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      env:
        - image=ubuntu:static-analysis
    - os: linux
      sudo: required
      services: docker
      env:
        - image=debian
    - os: osx
      osx_image: xcode9
      env:
        - package=pairinteraction-install-osx.dmg
        - package_whl=pairinteraction-py3-none-macosx_10_12_x86_64.whl
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-4.3.11-MacOSX-x86_64.sh -O miniconda.sh
        - chmod +x miniconda.sh && ./miniconda.sh -b -p $HOME/miniconda3 && source $HOME/miniconda3/bin/activate root
        - wget https://github.com/pairinteraction/pairinteraction-build-dependencies/releases/download/1500989872/python-packages-osx.zip
        - unzip python-packages-osx.zip
        - conda config --prepend channels file:///$TRAVIS_BUILD_DIR/conda-export
        - brew update
      install:
        - conda install -y -q nomkl pairinteraction-dependencies
        - conda update -y -q setuptools wheel
        - pip install git+https://github.com/pyinstaller/pyinstaller.git@5b6288b4e6c594dd695a2bd5db67aa260b771ce5 # TODO if new version that supports python 3.6 without bugs in conda-forge, specify version of pyinstaller and include pyinstaller in conda-export
        - brew install gsl llvm@3.9 swig
        - npm install -g fileicon
      before_script:
        - export CXX=/usr/local/opt/llvm@3.9/bin/clang++
        - export LDFLAGS="-L/usr/local/opt/llvm@3.9/lib -Wl,-rpath,/usr/local/opt/llvm@3.9/lib,-rpath,${CONDA_PREFIX}/lib"
    - os: linux
      sudo: required
      services: docker
      env:
        - image=ubuntu
        - package=pairinteraction-install-ubuntu-xenial.deb
      before_deploy: sudo chown travis:travis $TRAVIS_BUILD_DIR/build/$package
    - os: linux
      sudo: required
      services: docker
      env:
        - image=ubuntu:bionic
        - package=pairinteraction-install-ubuntu-bionic.deb
      before_deploy: sudo chown travis:travis $TRAVIS_BUILD_DIR/build/$package
    - os: linux
      sudo: required
      services: docker
      addons:
        apt:
          packages:
            - pyqt5-dev-tools
      env:
        - image=manylinux
        - package_whl=pairinteraction-py3-none-manylinux1_x86_64.whl
    - os: linux
      sudo: required
      services: docker
      env:
        - image=opensuse
        - package=pairinteraction-install-opensuse.rpm
      before_deploy: sudo chown travis:travis $TRAVIS_BUILD_DIR/build/$package

script:
  - travis_wait 30 sleep infinity & ci/build_docker.sh

deploy:
  - provider: releases
    prerelease: true
    api_key: $GH_TOKEN
    file_glob: true
    file: $TRAVIS_BUILD_DIR/build/$package
    skip_cleanup: true
    on:
      tags: true
      condition: $package != ""
  - provider: releases
    prerelease: true
    api_key: $GH_TOKEN
    file_glob: true
    file: $TRAVIS_BUILD_DIR/build/$package_whl
    skip_cleanup: true
    on:
      tags: true
      condition: $package_whl != ""
