name: Windows

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 1' # Every Monday at 00:00
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 2
  CTEST_OUTPUT_ON_FAILURE: 1
  CMAKE_BUILD_TYPE: Release
  CXXFLAGS: "/W3 /Ox /arch:AVX2"
  QT_QPA_PLATFORM: "offscreen"
  QT_DEBUG_PLUGINS: 1

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ runner.os }}-cache-vcpkg-${{ github.run_id }}
          restore-keys:
            ${{ runner.os }}-cache-vcpkg-

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Patch intel-mkl portfile
        shell: pwsh
        run: |
          $PORTFILE = "$env:VCPKG_INSTALLATION_ROOT\ports\intel-mkl\portfile.cmake"
          (Get-Content $PORTFILE) -replace 'ilp64', 'lp64' | Out-File -encoding ASCII $PORTFILE

      - name: Configure
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S . -B build/ -G "Visual Studio 16 2019" -DBUILD_TESTING=On ^
              -DPython3_FIND_REGISTRY=LAST ^
              -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} ^
              -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE ^
              -DMKL_THREADING=intel_thread ^
              -DCMAKE_TOOLCHAIN_FILE="%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake"

      - name: Build
        run: cmake --build build/ --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: After build
        run: |
          $RedistVersion = Get-Content "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt" -TotalCount 1
          Copy-Item -Path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\$($RedistVersion.Trim())\vcredist_x64.exe" -Destination vcredist_x64.exe -Verbose
          cmake --build . --target win32 --config ${{ env.CMAKE_BUILD_TYPE }}
          python setup.py bdist_wheel --python-tag py3 --plat-name win_amd64
          $env:PATH_WHEEL_UNMODIFIED=$(ls dist\*.whl | foreach { $_.FullName })
          wheel unpack $env:PATH_WHEEL_UNMODIFIED -d wheelhouse\
          $env:PATH_WHEEL_UNPACKED=$(ls wheelhouse\* | foreach { $_.FullName })
          Copy-Item pairinteraction\Release\* ${env:PATH_WHEEL_UNPACKED}\pairinteraction\ -Recurse -Force -Verbose
          Remove-Item –path $env:PATH_WHEEL_UNPACKED\*.dist-info\RECORD
          wheel pack $env:PATH_WHEEL_UNPACKED -d wheelhouse\
        working-directory: build/

      - name: Tests
        run: |
          Copy-Item pairinteraction\Release\* pairinteraction\ -Recurse -Force -Verbose
          New-Item -Path pairinteraction\unit_test\Release\ -ItemType Directory -Force
          Copy-Item pairinteraction\Release\* pairinteraction\unit_test\Release -Recurse -Force -Verbose
          cmake --build . --target RUN_TESTS --config ${{ env.CMAKE_BUILD_TYPE }}
        working-directory: build/

      - name: Run debugging session in tmate
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && always()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - uses: actions/upload-artifact@v3
        with:
          name: pairinteraction-install-windows.exe
          path: build/pairinteraction-install-windows.exe
      - uses: actions/upload-artifact@v3
        with:
          name: pairinteraction-windows-wheel
          path: build/wheelhouse/*.whl
